# Generated by Django 4.2.9 on 2024-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_limited",
            field=models.BooleanField(default=False, verbose_name="ограниченный тираж"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_product_of_the_day",
            field=models.BooleanField(default=False, verbose_name="товар дня"),
        ),
    ]
