# Generated by Django 4.2.9 on 2024-03-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description",
            field=models.TextField(null=True, verbose_name="описания"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="name",
            field=models.CharField(max_length=512, verbose_name="названия"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описания"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=512, unique=True, verbose_name="наименования"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="описания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="наименования"),
        ),
    ]
