# Generated by Django 4.2.9 on 2024-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_is_limited_product_is_product_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(null=True, verbose_name="описание"),
        ),
    ]
