# Generated by Django 4.2.9 on 2024-03-31 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"verbose_name": "предложения", "verbose_name_plural": "предложение"},
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "продавец", "verbose_name_plural": "продавцы"},
        ),
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shops.models.shop_logo_directory_path,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
                verbose_name="логотип компании",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="пользователь"
            ),
        ),
    ]
