# Generated by Django 4.2.11 on 2024-04-04 19:57

from django.db import migrations, models
import settings_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="paginate_products_by",
            field=models.PositiveIntegerField(default=8, verbose_name="количество товаров на странице"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email_access_settings",
            field=models.JSONField(
                default=settings_app.models.get_default_email_settings,
                help_text="Email access settings from .env",
                verbose_name="настройки e-mail",
            ),
        ),
    ]
