# Generated by Django 4.2.9 on 2024-03-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=255, verbose_name="Имя файла импорта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе выполнения"),
                            ("completed", "Выполнен"),
                            ("error", "Завершён с ошибкой"),
                        ],
                        max_length=25,
                        verbose_name="Статус",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Время начала импорта")),
            ],
            options={
                "verbose_name": "лог импорта",
                "verbose_name_plural": "логи импорта",
            },
        ),
        migrations.CreateModel(
            name="ImportLogProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("import_log", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="imports.importlog")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "verbose_name": "продукт в логе импорта",
                "verbose_name_plural": "продукты в логах импорта",
            },
        ),
        migrations.AddField(
            model_name="importlog",
            name="products",
            field=models.ManyToManyField(
                related_name="import_logs", through="imports.ImportLogProduct", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="importlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
